export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_FEEDS_SUCCESS = 'LOAD_FEEDS_SUCCESS';
export const UPDATE_ITEM_SUCCESS = 'UPDATE_ITEM_SUCCESS';
export const SAVE_ITEM_SUCCESS = 'SAVE_ITEM_SUCCESS';
export const REMOVE_ITEM_SUCCESS = 'REMOVE_ITEM_SUCCESS';
